In [1]:
import pandas as pd
import re
from tqdm import tqdm
import math
import numpy as np
import json
from ast import literal_eval
import csv

In [2]:
def change(s):
    return s[0]

In [3]:
df_father = pd.read_excel("father1.xlsx")
df_father.drop("Unnamed: 0", inplace=True, axis=1)
df_father['last_name'] = df_father['subject'].apply(change)
df_father['full_name'] = df_father['last_name'] + df_father['name_string']

In [4]:
group = df_father.groupby('content_id')
df = pd.DataFrame(columns = ['content_id', 'index', 'kinrel', 'type', 'kin','time', 'name', 'subject'])

In [5]:
for g in tqdm(group):
    index_list = []
    kin_list = []
    name_list = []
    kinrel_list = []
    type_list = []
    time_list = []
    content_id = g[0]
    for index in g[1].index:
        index_list.append(df_father.loc[index]['index'])
        name_list.append(df_father.loc[index]['full_name'])
        kinrel_list.append(df_father.loc[index]['kinrel'])
        kin_list.append(df_father.loc[index]['kin'])
        type_list.append(df_father.loc[index]['type'])
        time_list.append(df_father.loc[index]['time'])
        subject = df_father.loc[index, 'subject']
    dict = {'content_id':content_id, 'index': index_list,'kinrel': kinrel_list, 'type': type_list, 'kin': kin_list, 'time': time_list,'name': name_list, 'subject' : subject}
    df = df.append(dict, ignore_index=True)

100%|██████████| 2626/2626 [00:07<00:00, 331.66it/s]

In [6]:
for index in df.index:
    row = df.loc[index]
    row['index'].insert(0, "-")
    row['kin'].insert(0, "墓主")
    row['name'].insert(0, row['subject'])
    row['kinrel'].insert(0, "O") # O represent 墓主
    row['type'].insert(0, "P")
    row['time'].insert(0, 0)

In [7]:
df

,content_id,index,kinrel,type,kin,time,name,subject
0,4966920,"[-, 15847]","[O, FFFF]","[P, P]","[墓主, 高祖]","[0, 120]","[劉崇俊, 劉升調]",劉崇俊
1,4966978,"[-, 70792, 70792, 70793, 70792]","[O, FFF, FF, F, FFFF]","[P, P, P, P, P]","[墓主, 曾祖, 祖, 考, 高祖]","[0, 90, 60, 30, 120]","[陶敬宣, 陶琳, 陶晟, 陶雅, 陶復]",陶敬宣
2,4966982,"[-, 70810, 70805, 70805, 70805, 70806, 70805]","[O, F, FFFF, FFF, FF, F, G-5]","[P, P, P, P, P, P, P]","[墓主, 考, 高祖, 曾祖, 祖, 考, 五代祖]","[0, 30, 120, 90, 60, 30, 150]","[賈潭, 賈行, 賈穜, 賈昶, 賈琛, 賈翊, 賈孫]",賈潭
3,4966988,"[-, 70819]","[O, F]","[P, P]","[墓主, 考]","[0, 30]","[江文蔚, 江秦]",江文蔚
4,4966994,"[-, 15877, 15876]","[O, F, FF]","[P, P, P]","[墓主, 考, 祖]","[0, 30, 60]","[常脩子, 常脩, 常泓]",常脩子
...,...,...,...,...,...,...,...,...
2621,8717747,"[-, 1476]","[O, F]","[P, P]","[墓主, 父]","[0, 30]","[王克俊, 王輔]",王克俊
2622,8717757,"[-, 15928, 15928, 15928]","[O, FFF, FF, F]","[P, P, P, P]","[墓主, 曾祖, 祖, 父]","[0, 90, 60, 30]","[鄭國寶、鄭國瑞, 鄭宗顔, 鄭棫, 鄭易]",鄭國寶、鄭國瑞
2623,8717762,"[-, 15900, 15902]","[O, F, FFB–]","[P, P, P]","[墓主, 父, 叔祖]","[0, 30, 60]","[洪儆, 洪梠, 洪内翰]",洪儆
2624,8717772,"[-, 15883]","[O, FF]","[P, P]","[墓主, 祖]","[0, 60]","[吳今鈁, 吳綽]",吳今鈁
2625,8717777,"[-, 1466, 1470]","[O, F, F]","[P, P, P]","[墓主, 父, 父]","[0, 30, 30]","[李輝女, 李輝, 李病革]",李輝女

In [8]:
df_yuefu = pd.read_excel("yuefu1.xlsx")
df_yuefu.drop("Unnamed: 0", inplace=True, axis=1)

In [9]:
group = df_yuefu.groupby('content_id')
for g in tqdm(group):
    index_list = []
    kin_list = []
    name_list = []
    kinrel_list = []
    type_list = []
    time_list = []
    content_id = g[0]
    content_list = df['content_id']
    for index in g[1].index:
        name_list.append(df_yuefu.loc[index]['yuefu'])
        index_list.append(df_yuefu.loc[index]['index'])
        kinrel_list.append(df_yuefu.loc[index]['kinrel'])
        type_list.append(df_yuefu.loc[index]['type'])
        time_list.append(df_yuefu.loc[index]['time'])
        kin_list.append('岳父')
        subject = df_yuefu.loc[index]['subject']
    if content_id in content_list.values:
        count = df[df['content_id'] == content_id].index[0]
        for index in index_list:
            df.loc[count]['index'].append(index)
        for kin in kin_list:
            df.loc[count]['kin'].append(kin)
        for name in name_list:
            df.loc[count]['name'].append(name)
        for kinrel in kinrel_list:
            df.loc[count]['kinrel'].append(kinrel)
        for type in type_list:
            df.loc[count]['type'].append(type)
        for time in time_list:
            df.loc[count]['time'].append(time)
    else:
        index_list.insert(0, "-")
        kin_list.insert(0, "墓主")
        name_list.insert(0, subject)
        kinrel_list.insert(0, "O")
        type_list.insert(0, "P")
        time_list.insert(0, 0)
        dict = {'content_id':content_id, 'index': index_list,'kinrel': kinrel_list, 'type': type_list, 'kin': kin_list, 'time': time_list,'name': name_list, 'subject' : subject}
        df = df.append(dict, ignore_index=True)

100%|██████████| 419/419 [00:00<00:00, 547.66it/s]

In [10]:
df

,content_id,index,kinrel,type,kin,time,name,subject
0,4966920,"[-, 15847]","[O, FFFF]","[P, P]","[墓主, 高祖]","[0, 120]","[劉崇俊, 劉升調]",劉崇俊
1,4966978,"[-, 70792, 70792, 70793, 70792]","[O, FFF, FF, F, FFFF]","[P, P, P, P, P]","[墓主, 曾祖, 祖, 考, 高祖]","[0, 90, 60, 30, 120]","[陶敬宣, 陶琳, 陶晟, 陶雅, 陶復]",陶敬宣
2,4966982,"[-, 70810, 70805, 70805, 70805, 70806, 70805]","[O, F, FFFF, FFF, FF, F, G-5]","[P, P, P, P, P, P, P]","[墓主, 考, 高祖, 曾祖, 祖, 考, 五代祖]","[0, 30, 120, 90, 60, 30, 150]","[賈潭, 賈行, 賈穜, 賈昶, 賈琛, 賈翊, 賈孫]",賈潭
3,4966988,"[-, 70819]","[O, F]","[P, P]","[墓主, 考]","[0, 30]","[江文蔚, 江秦]",江文蔚
4,4966994,"[-, 15877, 15876]","[O, F, FF]","[P, P, P]","[墓主, 考, 祖]","[0, 30, 60]","[常脩子, 常脩, 常泓]",常脩子
...,...,...,...,...,...,...,...,...
2770,8711502,"[-, 17704]","[O, WF]","[P, NP]","[墓主, 岳父]","[0, 30]","[趙仲瞞, 康德隆]",趙仲瞞
2771,8712137,"[-, 17434]","[O, WF]","[P, NP]","[墓主, 岳父]","[0, 30]","[晏殊女、富弼妻, 李虚已]",晏殊女、富弼妻
2772,8712167,"[-, 17586]","[O, WF]","[P, NP]","[墓主, 岳父]","[0, 30]","[劉幾, 孫僅]",劉幾
2773,8713417,"[-, 16646]","[O, WF]","[P, NP]","[墓主, 岳父]","[0, 30]","[富直英, 吕直夫]",富直英
2774,8715267,"[-, 1875]","[O, WF]","[P, NP]","[墓主, 岳父]","[0, 30]","[應次昭, 應宏甫]",應次昭

In [11]:
df_son = pd.read_excel("son1.xlsx")
df_son.drop("Unnamed: 0", inplace=True, axis=1)
df_son['last_name'] = df_son['subject'].apply(change)
df_son = df_son[df_son['name_string'] != "[]"]
df_son = df_son[df_son['name_string'] != "["]
df_son['people'] = ''
for index in tqdm(df_son.index):
    last = df_son.loc[index]['last_name']
    people = []
    name_string = df_son.loc[index]['name_string']
    if name_string[0] == "[":
        name_string = literal_eval(name_string)
    for name in name_string:
        if "某" not in name:
            full_name = last + name
            people.append(full_name) 
    df_son.loc[index, 'people'] = str(people)

100%|██████████| 4401/4401 [00:01<00:00, 2425.56it/s]

In [12]:
group = df_son.groupby('content_id')
for g in tqdm(group):
    index_list = []
    kin_list = []
    name_list = []
    kinrel_list = []
    type_list = []
    time_list = []
    content_id = g[0]
    content_list = df['content_id']
    for index in g[1].index:
        namelist = df_son.loc[index]['people']
        namelist = literal_eval(namelist)
        for name in namelist:
            index_list.append(df_son.loc[index]['index'])
            name_list.append(name)
            kin_list.append(df_son.loc[index]['kin'])
            kinrel_list.append(df_son.loc[index]['kinrel'])
            type_list.append(df_son.loc[index]['type'])
            time_list.append(df_son.loc[index]['time'])
        subject = df_son.loc[index, 'subject']
    if content_id in content_list.values:
        count = df[df['content_id'] == content_id].index[0]
        for index in index_list:
            df.loc[count]['index'].append(index)
        for kin in kin_list:
            df.loc[count]['kin'].append(kin)
        for name in name_list:
            df.loc[count]['name'].append(name)
        for kinrel in kinrel_list:
            df.loc[count]['kinrel'].append(kinrel)
        for type in type_list:
            df.loc[count]['type'].append(type)
        for time in time_list:
            df.loc[count]['time'].append(time)
    else:
        index_list.insert(0, "-")
        kin_list.insert(0, "墓主")
        name_list.insert(0, subject)
        kinrel_list.insert(0, "O")
        type_list.insert(0, "P")
        time_list.insert(0, 0)
        dict = {'content_id':content_id, 'index': index_list,'kinrel': kinrel_list, 'type': type_list, 'kin': kin_list, 'time': time_list,'name': name_list, 'subject' : subject}
        df = df.append(dict, ignore_index=True)

100%|██████████| 2931/2931 [00:12<00:00, 226.10it/s]

In [13]:
df

,content_id,index,kinrel,type,kin,time,name,subject
0,4966920,"[-, 15847, 15860, 15860, 15860, 15860, 15860, ...","[O, FFFF, S, S, S, S, S, S, S, S]","[P, P, P, P, P, P, P, P, P, P]","[墓主, 高祖, 子, 子, 子, 子, 子, 子, 子, 子]","[0, 120, -30, -30, -30, -30, -30, -30, -30, -30]","[劉崇俊, 劉升調, 劉子, 劉子節, 劉範, 劉簡, 劉策, 劉霸, 劉時, 劉符]",劉崇俊
1,4966978,"[-, 70792, 70792, 70793, 70792]","[O, FFF, FF, F, FFFF]","[P, P, P, P, P]","[墓主, 曾祖, 祖, 考, 高祖]","[0, 90, 60, 30, 120]","[陶敬宣, 陶琳, 陶晟, 陶雅, 陶復]",陶敬宣
2,4966982,"[-, 70810, 70805, 70805, 70805, 70806, 70805]","[O, F, FFFF, FFF, FF, F, G-5]","[P, P, P, P, P, P, P]","[墓主, 考, 高祖, 曾祖, 祖, 考, 五代祖]","[0, 30, 120, 90, 60, 30, 150]","[賈潭, 賈行, 賈穜, 賈昶, 賈琛, 賈翊, 賈孫]",賈潭
3,4966988,"[-, 70819]","[O, F]","[P, P]","[墓主, 考]","[0, 30]","[江文蔚, 江秦]",江文蔚
4,4966994,"[-, 15877, 15876]","[O, F, FF]","[P, P, P]","[墓主, 考, 祖]","[0, 30, 60]","[常脩子, 常脩, 常泓]",常脩子
...,...,...,...,...,...,...,...,...
3713,8716777,"[-, 16093, 16093, 16093, 16093, 16093, 16093, ...","[O, S, S, S, S, S, S, S, S, S, S, S, S, S, S, ...","[P, P, P, P, P, P, P, P, P, P, P, P, P, P, P, ...","[墓主, 男, 男, 男, 男, 男, 男, 男, 男, 男, 男, 男, 男, 男, 男,...","[0, -30, -30, -30, -30, -30, -30, -30, -30, -3...","[毛仁靜, 毛宜老, 毛雙老, 毛大老, 毛翀老, 毛君錫, 毛顔老, 毛宗憑, 毛偉老, ...",毛仁靜
3714,8717027,"[-, 16080]","[O, S]","[P, P]","[墓主, 子]","[0, -30]","[項璡, 項立信]",項璡
3715,8717112,"[-, 1558, 1558, 1558, 1558, 1558, 1557, 1557]","[O, S, S, S, S, S, S, S]","[P, P, P, P, P, P, P, P]","[墓主, 男, 男, 男, 男, 男, 男, 男]","[0, -30, -30, -30, -30, -30, -30, -30]","[杜文甫, 杜福翁, 杜平翁, 杜延翁, 杜壽翁, 杜同翁, 杜元, 杜龍]",杜文甫
3716,8717312,"[-, 16021, 16021, 16023, 16023]","[O, S, S, SS, SS]","[P, P, P, P, P]","[墓主, 子, 子, 孫, 孫]","[0, -30, -30, -60, -60]","[任顥, 任庚, 任康, 任之才, 任之美]",任顥
3717,8717507,"[-, 15979, 15979, 15983, 15983, 15981, 15981, ...","[O, S, S, SSS, SSS, SS, SS, SS, SS]","[P, P, P, P, P, P, P, P, P]","[墓主, 子, 子, 曾孫, 曾孫, 孫, 孫, 孫, 孫]","[0, -30, -30, -90, -90, -60, -60, -60, -60]","[梁全本, 梁恭, 梁閏, 梁蘿頭, 梁婆奴, 梁琮, 梁章, 梁彦, 梁筠]",梁全本

In [14]:
df_daughter = pd.read_excel("daughter1.xlsx")
df_daughter.drop("Unnamed: 0", inplace=True, axis=1)
df_daughter = df_daughter[df_daughter['name_string'] != "[]"]
df_daughter = df_daughter[df_daughter['name_string'] != "["]
df_daughter = df_daughter[df_daughter['name_string'] != "]"]
df_daughter['people'] = ''
for index in tqdm(df_daughter.index):
    people = []
    name_string = df_daughter.loc[index]['name_string']
    if name_string[0] == "[":
        name_string = literal_eval(name_string)
    for name in name_string:
        if "某" not in name and name != "在室" and "氏" not in name and "CF" not in name:
            if len(name) >= 2:
                people.append(name) 
    df_daughter.loc[index, 'people'] = str(people)

100%|██████████| 2783/2783 [00:00<00:00, 3399.86it/s]

In [15]:
group = df_daughter.groupby('content_id')
for g in tqdm(group):
    index_list = []
    kin_list = []
    name_list = []
    kinrel_list = []
    type_list = []
    time_list = []
    content_id = g[0]
    content_list = df['content_id']
    for index in g[1].index:
        namelist = df_daughter.loc[index]['people']
        namelist = literal_eval(namelist)
        for name in namelist:
            index_list.append(df_daughter.loc[index]['index'])
            name_list.append(name)
            kin_list.append(df_daughter.loc[index]['kin'] + "適")
            kinrel_list.append(df_daughter.loc[index]['kinrel'])
            type_list.append(df_daughter.loc[index]['type'])
            time_list.append(df_daughter.loc[index]['time'])
        subject = df_daughter.loc[index, 'subject']
    if content_id in content_list.values:
        count = df[df['content_id'] == content_id].index[0]
        for index in index_list:
            df.loc[count]['index'].append(index)
        for kin in kin_list:
            df.loc[count]['kin'].append(kin)
        for name in name_list:
            df.loc[count]['name'].append(name)
        for kinrel in kinrel_list:
            df.loc[count]['kinrel'].append(kinrel)
        for type in type_list:
            df.loc[count]['type'].append(type)
        for time in time_list:
            df.loc[count]['time'].append(time)
    else:
        if len(index_list) >= 1:
            index_list.insert(0, "-")
            kin_list.insert(0, "墓主")
            name_list.insert(0, subject)
            kinrel_list.insert(0, "O")
            type_list.insert(0, "P")
            time_list.insert(0, 0)
            dict = {'content_id':content_id, 'index': index_list,'kinrel': kinrel_list, 'type': type_list, 'kin': kin_list, 'time': time_list,'name': name_list, 'subject' : subject}
            df = df.append(dict, ignore_index=True)

100%|██████████| 2289/2289 [00:05<00:00, 408.79it/s]

In [16]:
df

,content_id,index,kinrel,type,kin,time,name,subject
0,4966920,"[-, 15847, 15860, 15860, 15860, 15860, 15860, ...","[O, FFFF, S, S, S, S, S, S, S, S]","[P, P, P, P, P, P, P, P, P, P]","[墓主, 高祖, 子, 子, 子, 子, 子, 子, 子, 子]","[0, 120, -30, -30, -30, -30, -30, -30, -30, -30]","[劉崇俊, 劉升調, 劉子, 劉子節, 劉範, 劉簡, 劉策, 劉霸, 劉時, 劉符]",劉崇俊
1,4966978,"[-, 70792, 70792, 70793, 70792]","[O, FFF, FF, F, FFFF]","[P, P, P, P, P]","[墓主, 曾祖, 祖, 考, 高祖]","[0, 90, 60, 30, 120]","[陶敬宣, 陶琳, 陶晟, 陶雅, 陶復]",陶敬宣
2,4966982,"[-, 70810, 70805, 70805, 70805, 70806, 70805, ...","[O, F, FFFF, FFF, FF, F, G-5, D1H, D1H]","[P, P, P, P, P, P, P, NP, NP]","[墓主, 考, 高祖, 曾祖, 祖, 考, 五代祖, 長女適, 長女適]","[0, 30, 120, 90, 60, 30, 150, -30, -30]","[賈潭, 賈行, 賈穜, 賈昶, 賈琛, 賈翊, 賈孫, 楊元鼎, 不幸]",賈潭
3,4966988,"[-, 70819]","[O, F]","[P, P]","[墓主, 考]","[0, 30]","[江文蔚, 江秦]",江文蔚
4,4966994,"[-, 15877, 15876]","[O, F, FF]","[P, P, P]","[墓主, 考, 祖]","[0, 30, 60]","[常脩子, 常脩, 常泓]",常脩子
...,...,...,...,...,...,...,...,...
3882,8713197,"[-, 16848, 16848, 16848, 16848]","[O, D1H, DH, DH, DH]","[P, NP, NP, NP, NP]","[墓主, 長女適, 女適, 女適, 女適]","[0, -30, -30, -30, -30]","[劉孝從妻, 栝蒼, 王佐, 妻栝蒼, 何璹]",劉孝從妻
3883,8713272,"[-, 16813]","[O, DH]","[P, NP]","[墓主, 女適]","[0, -30]","[章惇女、竇訥妻, 劉範]",章惇女、竇訥妻
3884,8716297,"[-, 16118, 16118]","[O, DH, DH]","[P, NP, NP]","[墓主, 女適, 女適]","[0, -30, -30]","[車申, 林諤, 男進]",車申
3885,8716542,"[-, 1704, 1704, 1704]","[O, DH, DH, DH]","[P, NP, NP, NP]","[墓主, 女適, 女適, 女適]","[0, -30, -30, -30]","[陳文廣, 單夢葉, 趙汝■, 趙祟審]",陳文廣
3886,8717522,"[-, 15975]","[O, DH]","[P, NP]","[墓主, 女適]","[0, -30]","[殘, [][]",殘

In [17]:
df_zangdi = pd.read_excel("zangdi.xlsx")
df_zangdi.drop("Unnamed: 0", inplace=True, axis=1)

In [18]:
df_zangdi

      content_id           sent first        second          x         y
0        5749297       于餘杭縣蔡家之塢   NaN        ['餘杭']  119.94060  30.27177
1        5583141   于懷安縣稷下里崇福山之原   NaN  ['福山', '懷安']  107.83250  36.64270
2        5578423    於岷山廣濟鄉永寧里新兆   NaN  ['永寧', '廣濟']  111.65340  34.38581
3        5578313  于臨江軍城南筠山盛安人之塋   臨江軍        ['安人']  115.39899  28.01557
4        5455882         於白神山佛舍   NaN        ['神山']  111.84244  35.96744
...          ...            ...   ...           ...        ...       ...
3037     5261132          爲分寧著姓    分寧           NaN  114.55963  29.03871
3038     5165557        眉州眉山之著姓    眉州           NaN  103.83146  30.05050
3039     5068183   漢雍奴侯恂本上谷昌平著姓    昌平           NaN  116.22370  40.22210
3040     5037384        爲建州建安著姓    建安           NaN  118.32378  27.03886
3041     5037167       今爲青州益都著姓    青州           NaN  118.47810  36.69748

[3042 rows x 6 columns]

In [19]:
group = df_zangdi.groupby("content_id")
for g in tqdm(group):
    place_list = []
    content_id = g[0]
    content_list = df['content_id']
    for index in g[1].index:
        x = df_zangdi.loc[index, 'x']
        y = df_zangdi.loc[index, 'y']
    if content_id in content_list.values:
        count = df[df['content_id'] == content_id].index[0]
        df.loc[count, 'x'] = x
        df.loc[count, 'y'] = y

100%|██████████| 2695/2695 [00:01<00:00, 1398.19it/s]

In [20]:
df_time = pd.read_excel("time.xlsx")
df_time.drop("Unnamed: 0", inplace=True, axis=1)

In [21]:
for index in tqdm(df_time.index):
    row = df_time.loc[index]
    content_list = df['content_id']
    if row['content_id'] in content_list.values:
        count = df[df['content_id'] == row['content_id']].index[0]
        #df.loc[count, 'nianhao'] = row['nianhao']
        df.loc[count, 'year'] = row['time']

100%|██████████| 3196/3196 [00:03<00:00, 1003.04it/s]

In [22]:
df.sample(20)

,content_id,index,kinrel,type,kin,time,name,subject,x,y,year
1401,5583434,"[-, 39794, 39793, 39797, 39797, 39797, 39778]","[O, FFF, FF, S, S, S, S]","[P, P, P, P, P, P, P]","[墓主, 曾祖, 祖, 男, 男, 男, 子]","[0, 90, 60, -30, -30, -30, -30]","[宋适, 宋良弼, 宋舜臣, 宋世譽, 宋世儒, 宋世求, 宋與仲]",宋适,NaN,NaN,NaN
2472,5956602,"[-, 18615, 18614, 18613, 18618, 18619]","[O, F, FF, FFF, S, DH]","[P, P, P, P, P, NP]","[墓主, 父, 大父, 曾大父, 子男, 一女適]","[0, 30, 60, 90, -30, -30]","[章祖義, 章鑄, 章櫄, 章詡, 章碩穎, 洪先生]",章祖義,NaN,NaN,NaN
1558,5654257,"[-, 37189, 37190, 37189, 37193, 37191, 37191, ...","[O, FF, F, FFF, SS, S, S, DH, DH, DH]","[P, P, P, P, P, P, P, NP, NP, NP]","[墓主, 祖, 父, 曾祖, 孫, 子男, 子男, 女適, 女適, 女適]","[0, 60, 30, 90, -60, -30, -30, -30, -30, -30]","[吳燠, 吳偲, 吳概, 吳常陸, 吳鉉, 吳垣, 吳堮, 沈韶, 万俟侃, 陳汶]",吳燠,NaN,NaN,NaN
190,5062385,"[-, 67194, 67193, 67193, 67196, 67196, 67196]","[O, F, FFF, FF, S, S, S]","[P, P, P, P, P, P, P]","[墓主, 父, 皇曾祖, 祖, 子, 子, 子]","[0, 30, 90, 60, -30, -30, -30]","[梅詢, 梅邈, 梅超, 梅遠, 梅鼎臣, 梅至, 梅寶臣]",梅詢,108.90698,34.24642,1004.0
493,5141428,"[-, 60683, 60686, 60686]","[O, FF, DH, DH]","[P, P, NP, NP]","[墓主, 祖, 一女適, 女適]","[0, 60, -30, -30]","[王洙妻, 王安, 陳安道, 陳安道]",王洙妻,115.88795,34.51082,1066.0
955,5316933,"[-, 49808, 49805, 49804]","[O, F, F, FF]","[P, P, P, P]","[墓主, 父, 考, 祖]","[0, 30, 30, 60]","[王雯, 王慥, 王起, 王淮]",王雯,112.38263,34.66528,1097.0
1661,5689927,"[-, 34886, 34885, 34884, 34897]","[O, F, FF, FFF, DH]","[P, P, P, P, NP]","[墓主, 父, 祖, 曾祖, 女適]","[0, 30, 60, 90, -30]","[呂思恭, 呂興祖, 呂安道, 呂震, 張思義]",呂思恭,120.16862,30.29412,1150.0
3685,5965666,"[-, 18311, 18311]","[O, S, S]","[P, P, P]","[墓主, 男, 男]","[0, -30, -30]","[陳塈, 陳天儒, 陳天民]",陳塈,NaN,NaN,NaN
3535,5795159,"[-, 27795, 27793, 27793]","[O, S, S, S]","[P, P, P, P]","[墓主, 子, 子, 子]","[0, -30, -30, -30]","[黃椿, 黃君, 黃變, 黃言]",黃椿,NaN,NaN,1150.0
3223,5338786,"[-, 48056, 48056, 48056]","[O, S, S, S]","[P, P, P, P]","[墓主, 子, 子, 子]","[0, -30, -30, -30]","[趙叔璫, 趙相之, 趙樞之, 趙及名]",趙叔璫,112.83702,34.16176,1104.0
1034,5339165,"[-, 47759, 47759, 47759, 47778]","[O, F, FF, FFF, DH]","[P, P, P, P, NP]","[墓主, 父, 大父, 曾大父, 女適]","[0, 30, 60, 90, -30]","[朱郢女, 朱郢, 朱維甫, 朱昭元, 俞美成]",朱郢女,118.85319,27.37210,1113.0
3700,8712972,"[-, 17087, 17087, 17085]","[O, SS, SS, S]","[P, P, P, P]","[墓主, 孫, 孫, 子男]","[0, -60, -60, -30]","[趙世職妻, 趙子詵, 趙子堅, 趙丙]",趙世職妻,112.38263,34.66528,NaN
2449,5945402,"[-, 3218, 3218, 3209, 3218]","[O, FF, F, F, FFF]","[P, P, P, P, P]","[墓主, 祖, 考, 考, 曾祖考]","[0, 60, 30, 30, 90]","[李淑英, 李考頤, 李季麒, 李官懼, 李知微]",李淑英,NaN,NaN,1256.0
1248,5480458,"[-, 43051, 43051, 43071, 43071, 43075, 43075, ...","[O, F, FFF, S, S, SSS, SSS, SSS, SSS, SS, SS, ...","[P, P, P, P, P, P, P, P, P, P, P, P, P, P, NP]","[墓主, 皇考, 皇曾祖, 子, 子, 曾孫, 曾孫, 曾孫, 曾孫, 孫, 孫, 孫, 孫...","[0, 30, 90, -30, -30, -90, -90, -90, -90, -60,...","[高世則妻, 高師錫, 高鼎, 高百之, 高温, 高不疏, 高不倚, 高不群, 高不若, 高...",高世則妻,NaN,NaN,1160.0
3032,5178739,"[-, 57919, 57919, 57919, 57919, 57920, 57920]","[O, S, S, S, S, D3H, D3H]","[P, P, P, P, P, NP, NP]","[墓主, 子, 子, 子, 子, 三女適, 三女適]","[0, -30, -30, -30, -30, -30, -30]","[程瑜, 程預, 程疾廢, 程顗, 程顓, 王師古, 賈芮]",程瑜,112.38263,34.66528,1063.0
904,5306309,"[-, 51398, 51408]","[O, FFF, SS]","[P, P, P]","[墓主, 曾祖, 孫]","[0, 90, -60]","[束端卿, 束勍, 束元矩]",束端卿,116.04670,36.16054,1110.0
3512,5765262,"[-, 28985]","[O, SS]","[P, P]","[墓主, 孫]","[0, -60]","[宋駒, 宋慧]",宋駒,NaN,NaN,NaN
2552,8713022,"[-, 17035, 17035, 17042, 17042, 17046, 17046, ...","[O, FF, F, S, S, SDH, SDH, SDH, SDH, DH, DH, DH]","[P, P, P, P, P, NP, NP, NP, NP, NP, NP, NP]","[墓主, 大父, 父, 男, 男, 孫女適, 孫女適, 孫女適, 孫女適, 女適, 女適, 女適]","[0, 60, 30, -30, -30, -60, -60, -60, -60, -30,...","[夏濬, 夏希皓, 夏承贊, 夏詵, 夏詔, 舒貫, [][, ]有, 年月日, 里宗翊, ...",夏濬,NaN,NaN,NaN
2598,8716457,"[-, 1727, 1731]","[O, F, DH]","[P, P, NP]","[墓主, 父, 女適]","[0, 30, -30]","[陳君玉, 陳良厚, 錢子忠]",陳君玉,120.09931,30.86496,1069.0
443,5133124,"[-, 61617, 61616, 61615, 61621, 61621, 61621, ...","[O, F, FF, FFF, S, S, S, S, S, S, S, S, S, D4H...","[P, P, P, P, P, P, P, P, P, P, P, P, P, NP, NP...","[墓主, 父, 大父, 曾大父, 男子, 男子, 男子, 男子, 男子, 男子, 子, 子,...","[0, 30, 60, 90, -30, -30, -30, -30, -30, -30, ...","[郭遘, 郭恩, 郭興, 郭弼, 郭棐, 郭始歲, 郭采, 郭歲, 郭槃, 郭歲, 郭蔭, ...",郭遘,108.90700,34.24642,1090.0

In [23]:
df.to_excel("muzhi.xlsx")

In [24]:
df_people = pd.DataFrame(columns = ['name', 'kinrel', 'type', 'content_id', 'time', 'x', 'y'])
for index in tqdm(df.index):
    kinrel_list = df.loc[index]['kinrel']
    type_list = df.loc[index]['type']
    name_list = df.loc[index]['name']
    x = df.loc[index]['x']
    y = df.loc[index]['y']
    content_id = df.loc[index]['content_id']
    time_list = df.loc[index]['time']
    year = df.loc[index]['year']
    length = len(kinrel_list)
    for i in range(length):
        kin = kinrel_list[i]
        type = type_list[i]
        name = name_list[i]
        time = year - time_list[i]
        dict = {'name': name, 'kinrel': kin, 'type':type, 'content_id': content_id, 'time':time, 'x':x, 'y':y}
        df_people = df_people.append(dict, ignore_index=True)

100%|██████████| 3887/3887 [00:59<00:00, 65.63it/s]

In [25]:
df_people.to_excel("people.xlsx")

In [26]:
df_people

      name kinrel type content_id    time         x        y
0      劉崇俊      O    P    4966920  1125.0  117.6684  32.8949
1      劉升調   FFFF    P    4966920  1005.0  117.6684  32.8949
2       劉子      S    P    4966920  1155.0  117.6684  32.8949
3      劉子節      S    P    4966920  1155.0  117.6684  32.8949
4       劉範      S    P    4966920  1155.0  117.6684  32.8949
...    ...    ...  ...        ...     ...       ...      ...
31056  單夢葉     DH   NP    8716542  1099.0       NaN      NaN
31057  趙汝■     DH   NP    8716542  1099.0       NaN      NaN
31058  趙祟審     DH   NP    8716542  1099.0       NaN      NaN
31059    殘      O    P    8717522     NaN       NaN      NaN
31060  [][     DH   NP    8717522     NaN       NaN      NaN

[31061 rows x 7 columns]

In [27]:
node_info = df.values.tolist()
with open('node.csv', 'w') as f:
    write = csv.writer(f)
    write.writerow(["id", "index", "kinrel","type","kin","name", "subject", "nianhao", "time", "x", "y"])
    write.writerows(node_info)

In [28]:
df.set_index("content_id", inplace=True)

In [29]:
placelist = df['x'].dropna().index
timelist = df['year'].dropna().index

In [30]:
global df_people
df_people = pd.DataFrame(columns = ['i','j','name_i','name_j','owner_i', 'owner_j','type_i','type_j','x_i','y_i','x_j','y_j','dvalue','d_result',
                                    'time_i','time_j','tvalue','t_result', 'kin_i', 'kin_j'])

In [31]:
def common_data(row1, row2, i, j):
    global df_people
    name1 = row1['name']
    name2 = row2['name']
    type1 = row1['type']
    type2 = row2['type']
    x1 = row1['x']
    x2 = row2['x']
    y1 = row1['y']
    y2 = row2['y']
    time1 = row1['time']
    time2 = row2['time']
    year1 = row1['year']
    year2 = row2['year'] 
    kin1 = row1['kinrel']
    kin2 = row2['kinrel']
    dscore = 0
    tscore = 0
    count = 0
    tresult = []
    dresult = []
    result_add = 0
    result_mul = 0
    
    dmax = 10
    tmax = 50
    
    for x in name1:
        position1 = name1.index(x)
        for y in name2:
            dscore = 0.5
            tscore = 0.5
            if x == y:
                count += 1
                position2 = name2.index(y)
                dict = {'i': i, 'j': j, "name_i": x, "name_j":y, "type_i": type1[position1], "type_j": type2[position2]}
                if i in placelist and j in placelist:
                    if (type1[position1] == "P") and (type2[position2] == "P"):
                        distance = (float(row['x']) - float(rowcompare['x']))** 2 + (float(row['y']) - float(rowcompare['y']))** 2
                        distance = math.sqrt(distance)
                        if distance <= dmax:
                            dscore = 1
                        else:
                            dscore = 0
                        dict['x_i'] = row['x']
                        dict['y_i'] = row['y']
                        dict['x_j'] = rowcompare['x']
                        dict['y_j'] = rowcompare['y']
                        dict['dvalue'] = distance
                if i in timelist and j in timelist:
                    timei = year1 - time1[position1]
                    timej = year2 - time2[position2]
                    time = abs(timei - timej)
                    if time <= tmax:
                        tscore = 1
                    else:
                        tscore = 0
                    dict['time_i'] = timei
                    dict['time_j'] = timej
                    dict['tvalue'] = time
                dresult.append(dscore)
                tresult.append(tscore)
                dict['d_result'] = dscore
                dict['t_result'] = tscore
                dict['kin_i'] = kin1[position1]
                dict['kin_j'] = kin2[position2]
                dict['owner_i'] = row['subject']
                dict['owner_j'] = rowcompare['subject']
                df_people = df_people.append(dict, ignore_index=True)
                result_add = result_add + tscore + dscore
                result_mul = result_mul + tscore * dscore
    
    return dresult, tresult, count, result_add, result_mul

In [32]:
graph = pd.DataFrame()
count = 1
for i in tqdm(df.index):
    row = df.loc[i]
    for j in df.index[count:]:
        rowcompare = df.loc[j]
        dresult, tresult, c, add, mul = common_data(row, rowcompare, i, j)
        if c != 0:
            dict = {'i': i, 'j': j, 'dresult': dresult, 'tresult':tresult, 'count':c, "add":add, "mul":mul}
            graph = graph.append(dict, ignore_index=True)
    count += 1

100%|██████████| 3887/3887 [14:11<00:00,  4.56it/s]

In [38]:
graph

              i          j          dresult     tresult  count  add   mul
0     4966920.0  4986357.0              [1]         [0]    1.0  1.0  0.00
1     4966920.0  5314831.0              [1]         [0]    1.0  1.0  0.00
2     4966920.0  5583222.0  [0.5, 0.5, 0.5]   [0, 0, 0]    3.0  1.5  0.00
3     4966920.0  5749393.0           [0, 0]      [1, 1]    2.0  2.0  0.00
4     4966920.0  5581182.0            [0.5]         [1]    1.0  1.5  0.50
...         ...        ...              ...         ...    ...  ...   ...
4402  8712147.0  5111407.0            [0.5]         [1]    1.0  1.5  0.50
4403  8713157.0  8713167.0       [0.5, 0.5]      [1, 1]    2.0  3.0  1.00
4404  8716687.0  5330030.0            [0.5]         [0]    1.0  0.5  0.00
4405  5122327.0  5122385.0            [0.5]       [0.5]    1.0  1.0  0.25
4406  5689972.0  5826850.0       [0.5, 0.5]  [0.5, 0.5]    2.0  2.0  0.50

[4407 rows x 7 columns]

In [42]:
graph.to_excel("graph.xlsx")
df_people.to_excel("people.xlsx")

In [40]:
graph['mul'].value_counts()

0.00     1335
0.50     1150
0.25     1138
1.00      445
2.00      101
1.50       56
0.75       49
3.00       33
2.50       21
4.00       18
1.25       14
1.75        8
3.50        6
4.50        5
5.00        4
7.00        3
10.00       3
5.50        3
6.00        2
7.50        2
2.25        2
2.75        1
14.00       1
6.50        1
3.75        1
9.00        1
20.50       1
4.75        1
3.25        1
13.00       1
Name: mul, dtype: int64

In [146]:
4967120 in df_time['content_id']

False

In [71]:
graph['distance'].value_counts()

-1.000000     2707
 0.000000      416
 1.964381       37
 0.559359       24
 0.678235       22
              ...
 16.260664       1
 16.831183       1
 1.358754        1
 0.414826        1
 0.459484        1
Name: distance, Length: 872, dtype: int64

In [72]:
graph['time'].value_counts()

-1.0      1845
 0.0        58
 2.0        51
 6.0        42
 8.0        42
          ...
 306.0       1
 258.0       1
 350.0       1
 247.0       1
 322.0       1
Name: time, Length: 281, dtype: int64

In [36]:
# 0 mean place not the same, 1 mean same place, -1 mean missing information
# 1485 not same, 467 same, 2447 missing information
# 2254 / 3885 Contain zangdi
count = 0
for edge in graph1:
    i = edge[0]
    j = edge[1]
    row = df.loc[i]
    rowcompare = df.loc[j]
    # check for zangdi
    if i in indexlist and j in indexlist:
        test = common_data(row['place'], rowcompare['place'])
        if test != 0:
            edge.append(1)
        else:
            edge.append(0)
    else:
        edge.append(-1)
    # check for zi-zi

NameError: name 'graph1' is not defined

In [ ]:
df

In [ ]:
def common_data(row1, row2):
    list1 = row1['name']
    list2 = row2['name']
    result = 0
    for x in list1:
        for y in list2:
            if x == y:
                if row1['kin'][list1.index(x)] == '子' and row2['kin'][list2.index(y)] == '子':
                    pass
                else:
                    result +=1                  
    return result

In [ ]:
with open('graph.csv', 'w') as f:
    write = csv.writer(f)
    write.writerow(["Source", "Target", "Type", "Weight"])
    write.writerows(graph)

In [ ]:
len(graph)